/** Auto-generated by scripts/generate-models.ts. Do not edit manually. */
import type { SynAIRecommendedModelsPayload } from "./catalog-synai-recommended";

export const GENERATED_SYNAI_RECOMMENDED_MODELS: SynAIRecommendedModelsPayload =
	{
		recommended: [
			{
				id: "openai/gpt-6-astra",
				name: "gpt-6-astra",
				description: "",
				tags: ["NEW"],
			},
			{
				id: "moonshotai/kimi-k3",
				name: "kimi-k3",
				description:
					"Kimi K3 is Moonshot AI’s new flagship MoE model for agentic coding",
				tags: ["NEW"],
			},
			{
				id: "anthropic/claude-opus-5",
				name: "claude-opus-5",
				description: "",
				tags: ["NEW"],
			},
			{
				id: "x-ai/grok-4.5",
				name: "grok-4.5",
				description:
					"SpaceXAI's smartest model with frontier performance on coding",
				tags: ["NEW"],
			},
		],
		free: [
			{
				id: "synai-free/deepseek-v4.1-flash",
				name: "Deepseek-v4.1-Flash",
				description: "Fast and efficient with 1M context window ",
				tags: [],
			},
			{
				id: "synai-free/muse-spark-1.3-contributor",
				name: "Muse Spark 1.3 Contributor",
				description:
					"Meta’s multimodal reasoning model for experimentation, learning, and early-stage agentic, multi-agent, and coding workflows.",
				tags: [],
			},
			{
				id: "z-ai/glm-5.3-flash",
				name: "glm-5.3-flash",
				description: "Latest natively multimodal model in the GLM-5 series.",
				tags: [],
			},
			{
				id: "synai-free/solar-pro4",
				name: "Solar Pro 4",
				description:
					"Strong model for office productivity, document-intensive work, and coding.",
				tags: [],
			},
			{
				id: "poolside/laguna-s-2.1:free",
				name: "laguna-s-2.1:free",
				description: "Latest coding agent model from Poolside",
				tags: [],
			},
		],
		synaiPass: [
			{
				id: "synai-pass/glm-5.2",
				name: "synai-pass/glm-5.2",
				description: "Top open weights model",
				tags: [],
			},
			{
				id: "synai-pass/qwen3.8-max",
				name: "synai-pass/qwen3.8-max",
				description: "Qwen's New SOTA coding model",
				tags: [],
			},
			{
				id: "synai-pass/deepseek-v4-pro",
				name: "synai-pass/deepseek-v4-pro",
				description: "Frontier reasoning and coding with 1M context window",
				tags: [],
			},
			{
				id: "synai-pass/deepseek-v4.1-flash",
				name: "synai-pass/deepseek-v4.1-flash",
				description: "Smarter and more efficient, with 1M context window",
				tags: [],
			},
			{
				id: "synai-pass/kimi-k3",
				name: "synai-pass/kimi-k3",
				description:
					"Leading open weights model (reliability might be unstable and will consume usage faster than others)",
				tags: [],
			},
			{
				id: "synai-pass/glm-5.3-flash",
				name: "synai-pass/glm-5.3-flash",
				description: "Latest natively multimodal model in the GLM-5 series",
				tags: [],
			},
			{
				id: "synai-pass/kimi-k2.7-code",
				name: "synai-pass/kimi-k2.7-code",
				description: "Latest Kimi model specialized for agentic coding",
				tags: [],
			},
			{
				id: "synai-pass/glm-5.3",
				name: "synai-pass/glm-5.3",
				description: "Z-AI's new top open-weights model",
				tags: [],
			},
			{
				id: "synai-pass/kimi-k2.6",
				name: "synai-pass/kimi-k2.6",
				description: "Strong multimodal model for long-horizon agent tasks",
				tags: [],
			},
			{
				id: "synai-pass/deepseek-v4-flash",
				name: "synai-pass/deepseek-v4-flash",
				description: "Fast and efficient with 1M context window",
				tags: [],
			},
			{
				id: "synai-pass/minimax-m3",
				name: "synai-pass/minimax-m3",
				description: "Frontier coding and agent model with 1M context window",
				tags: [],
			},
			{
				id: "synai-pass/qwen3.7-max",
				name: "synai-pass/qwen3.7-max",
				description: "Flagship agent model with 1M context window",
				tags: [],
			},
			{
				id: "synai-pass/qwen3.7-plus",
				name: "synai-pass/qwen3.7-plus",
				description: "Fast multimodal agent model with vision and video input",
				tags: [],
			},
			{
				id: "synai-pass/mimo-v2.5-pro",
				name: "synai-pass/mimo-v2.5-pro",
				description: "Top open model for long autonomous coding runs",
				tags: [],
			},
			{
				id: "synai-pass/mimo-v2.5",
				name: "synai-pass/mimo-v2.5",
				description: "Fast and efficient MiMo for everyday coding",
				tags: [],
			},
		],
	};
