import { SYNAI_SYSTEM_PROMPT_ACT_MODE } from "./act";
import { SYNAI_SYSTEM_PROMPT_YOLO_MODE } from "./yolo";

export const DEFAULT_SYNAI_SYSTEM_PROMPTS = {
	ACT: SYNAI_SYSTEM_PROMPT_ACT_MODE,
	YOLO: SYNAI_SYSTEM_PROMPT_YOLO_MODE,
};

export const DEFAULT_SYNAI_SYSTEM_PROMPT = SYNAI_SYSTEM_PROMPT_ACT_MODE;
